all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

    remote:
      hosts:
        vTestPC002:
          ansible_host: 10.0.47.2
        vTestPC003:
          ansible_host: 10.0.47.3
      vars:
        ansible_user: sys_conf_deb
        ansible_port: 22
